import 'dotenv/config';
import { defineConfig } from 'drizzle-kit';

// Drizzle Kit config. The schema file is generated by `drizzle-kit pull`
// (introspection of the live DB) and is the source of truth for future
// `generate`/`migrate`. Migrations + snapshots live alongside it in src/db/drizzle.
export default defineConfig({
	dialect: 'postgresql',
	schema: './src/db/drizzle/schema.ts',
	out: './src/db/drizzle',
	dbCredentials: {
		url: process.env.DATABASE_URL!
	},
	// Only manage the public schema; never touch internal/system schemas.
	schemaFilter: ['public'],
	// Keep generated SQL readable and deterministic.
	verbose: true,
	strict: true
});
