AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
    Function:
        Runtime: nodejs22.x
        Timeout: 30

Resources:
    UsersGet:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: lambdas/mad-users-get/src/
            Handler: index.handler
            Layers:
                - !Ref DbControllerLayer
            Events:
                Api:
                    Type: Api
                    Properties:
                        Path: /users/{userId}
                        Method: get

    DbControllerLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: mad-database-layer
            ContentUri: layers/mad-database-layer
            CompatibleRuntimes:
                - nodejs22.x
