AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
    Function:
        Runtime: nodejs22.x
        Timeout: 30

Resources:
    UsersGet:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: lambdas/mad-users-get/
            Handler: index.handler
            Layers:
                - !Ref DbControllerLayer
            Environment:
                Variables:
                    DB_HOST: ''
                    DB_PORT: ''
                    DB_NAME: ''
                    DB_USER: ''
                    DB_PASSWORD: ''
                    AWS_REGION: ''
            Events:
                Api:
                    Type: Api
                    Properties:
                        Path: /users/{userId}
                        Method: get

    UsersPost:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: lambdas/mad-users-post/
            Handler: index.handler
            Layers:
                - !Ref DbControllerLayer
            Environment:
                Variables:
                    DB_HOST: ''
                    DB_PORT: ''
                    DB_NAME: ''
                    DB_USER: ''
                    DB_PASSWORD: ''
                    AWS_REGION: ''
            Events:
                Api:
                    Type: Api
                    Properties:
                        Path: /users/
                        Method: post

    DbControllerLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: mad-database-layer
            ContentUri: layers/mad-database-layer
            CompatibleRuntimes:
                - nodejs22.x
