USB_VID = 0x239A
USB_PID = 0x80CA
USB_PRODUCT = "Matrix Portal M4 (Mile A Day)"
USB_MANUFACTURER = "Adafruit Industries LLC"

CHIP_VARIANT = SAMD51J19A
CHIP_FAMILY = samd51

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "S25FL116K, S25FL216K, GD25Q16C, W25Q16JVxQ"
LONGINT_IMPL = MPZ

CIRCUITPY_LTO_PARTITION = one

CIRCUITPY_AESIO = 0
CIRCUITPY_FLOPPYIO = 0
CIRCUITPY_PARALLELDISPLAYBUS = 0
CIRCUITPY_SHARPDISPLAY = 0
CIRCUITPY_ULAB = 0

# Include these Python libraries in firmware.
FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_ConnectionManager
FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_Requests
FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_ESP32SPI
FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_NeoPixel

# Mile A Day desk counter: drop what it never uses to make room for the app.
CIRCUITPY__BLEIO = 0
CIRCUITPY_ALARM = 0
CIRCUITPY_ANALOGIO = 0
CIRCUITPY_AUDIOBUSIO = 0
CIRCUITPY_AUDIOCORE = 0
CIRCUITPY_AUDIOIO = 0
CIRCUITPY_AUDIOMIXER = 0
CIRCUITPY_AUDIOMP3 = 0
CIRCUITPY_BITBANGIO = 0
CIRCUITPY_COUNTIO = 0
CIRCUITPY_EPAPERDISPLAY = 0
CIRCUITPY_FOURWIRE = 0
CIRCUITPY_FREQUENCYIO = 0
CIRCUITPY_GIFIO = 0
CIRCUITPY_I2CDISPLAYBUS = 0
CIRCUITPY_I2CTARGET = 0
CIRCUITPY_JPEGIO = 0
CIRCUITPY_KEYPAD = 0
CIRCUITPY_MSGPACK = 0
CIRCUITPY_ONEWIREIO = 0
CIRCUITPY_PS2IO = 0
CIRCUITPY_PULSEIO = 0
CIRCUITPY_PWMIO = 0
CIRCUITPY_ROTARYIO = 0
CIRCUITPY_RTC = 0
CIRCUITPY_SDCARDIO = 0
CIRCUITPY_SPITARGET = 0
CIRCUITPY_SYNTHIO = 0
CIRCUITPY_TOUCHIO = 0
CIRCUITPY_USB_HID = 0
CIRCUITPY_USB_MIDI = 0
CIRCUITPY_VECTORIO = 0
CIRCUITPY_WATCHDOG = 0
CIRCUITPY_ZLIB = 0
CIRCUITPY_TILEPALETTEMAPPER = 0
CIRCUITPY_PIXELMAP = 0
CIRCUITPY_RAINBOWIO = 0
CIRCUITPY_CODEOP = 0
CIRCUITPY_GETPASS = 0

# The app itself, frozen into flash (runs without using RAM for its code).
FROZEN_MPY_DIRS += $(TOP)/frozen/MAD_Desk
